# Tensors and Variables

In [3]:
import numpy as np
import tensorflow as tf

### Create Variable objects

In [4]:
# Create Variable objects of different type with tf.Variable

strings = tf.Variable(['Hello World'], tf.string)
floats = tf.Variable([3.14159, 2.71828], tf.float64)
ints = tf.Variable([1,2,3], tf.int32)
complexs = tf.Variable([25.9-7.39j, 1.23-4.91j], tf.complex128)

In [6]:
# Initialise a Variable value

tf.Variable(tf.constant(4.2, shape=(3,3)))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2]], dtype=float32)>

### Use and modify Variable values

In [7]:
v = tf.Variable(0.0)
w = v + 1 # w is a tf.Tensor which is computed based on the value of v

print(type(w))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
# Increment the value of a Variable

v.assign_add(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [9]:
# Decrement the value of a variable

v.assign_sub(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


# Create Tensor objects

Create a constant tensor as print its type as well as its shape:

In [10]:
# Create a constant Tensor

x = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print("dtype:", x.dtype)
print("shape:", x.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
dtype: <dtype: 'int32'>
shape: (3, 3)


In [11]:
# Obtain the value as a numpy array

x.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [13]:
x = tf.constant([[1,2,3], [4,5,6], [7,8,9]], dtype=tf.float32)
print(x.dtype)

<dtype: 'float32'>


In [14]:
# Create coefficients

coeffs = np.arange(16)

In [16]:
# Initialize shapes

shape1 = [8,2]
shape2 = [4,4]
shape3 = [2,2,2,2]

In [17]:
# Create Tensors of different shape

a = tf.constant(coeffs, shape=shape1)
print("\n a:\n ", a)

b = tf.constant(coeffs, shape=shape2)
print("\n b:\n ", b)

c = tf.constant(coeffs, shape=shape3)
print("\n b:\n ", c)


 a:
  tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]], shape=(8, 2), dtype=int64)

 b:
  tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int64)

 b:
  tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]], shape=(2, 2, 2, 2), dtype=int64)


### Useful Tensor operations

In [18]:
# Create a constant Tensor

t = tf.constant(np.arange(80), shape=[5,2,8])

In [19]:
# Get the rank of a Tensor

rank = tf.rank(t)

In [20]:
# Display the rank

print("rank: ", rank)

rank:  tf.Tensor(3, shape=(), dtype=int32)


In [22]:
# Reshape a Tensor

t2 = tf.reshape(t, [8,10])

In [29]:
# Create ones, zeros, identity and constant Tensors

ones = tf.ones(shape=(2,3))
zeros = tf.zeros(shape=(2,4))
eye = tf.eye(3)
tensor7 = tf.constant(7.0, shape=[2,2])

In [30]:
print("\n Ones:\n ", ones)
print("\n Zeros:\n ", zeros)
print("\n Identity:\n ", eye)
print("\n Tensor filled with 7:\n ", tensor7)


 Ones:
  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

 Zeros:
  tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)

 Identity:
  tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)

 Tensor filled with 7:
  tf.Tensor(
[[7. 7.]
 [7. 7.]], shape=(2, 2), dtype=float32)


In [31]:
# Create a ones Tensor and a zeros Tensor

t1 = tf.ones(shape=(2,2))
t2 = tf.zeros(shape=(2,2))

In [38]:
# Concatenate two Tensors

concat0 = tf.concat([t1, t2], 0)
concat1 = tf.concat([t1, t2], 1)

In [39]:
# Display the concatenated Tensors

print(concat0)
print(concat1)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]], shape=(2, 4), dtype=float32)


In [37]:
# Create a constant Tensor

t = tf.constant(np.arange(24), shape=(3, 2, 4))
print("t shape: ", t.shape)

t shape:  (3, 2, 4)


In [41]:
# Expanding the rank of Tensor

t1 = tf.expand_dims(t, 0)
t2 = tf.expand_dims(t, 1)
t3 = tf.expand_dims(t, 3)

In [47]:
# Display the shapes after tf.expand_dims

print("After expanding dims: \n t1 shape: ",
     t1.shape,
     "\n t2 shape: ",
     t2.shape,
     "\n t3 shape: ",
     t3.shape)

After expanding dims: 
 t1 shape:  (1, 3, 2, 4) 
 t2 shape:  (3, 1, 2, 4) 
 t3 shape:  (3, 2, 4, 1)


In [48]:
# Squeeze redundant dimensions

t1 = tf.squeeze(t1, 0)
t2 = tf.squeeze(t2, 1)
t3 = tf.squeeze(t3, 3)

In [50]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

(3, 2, 4)
(3, 2, 4)
(3, 2, 4)


In [51]:
# Sclicing a Tensor

x = tf.constant([1,2,3,4,5,6,7])

print(x[1:4])

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


#### Doing math with Tensors

In [52]:
# Create two constant Tensors

c = tf.constant([[1.0,2.0], [3.0,4.0]])
d = tf.constant([[1.0,1.0], [0.0,1.0]])

In [53]:
# Matrix multiplication

matmul_cd = tf.matmul(c, d)

In [54]:
# Display the result

matmul_cd

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [3., 7.]], dtype=float32)>

In [58]:
# Elementwise operations

c_times_d = c*d
c_plus_d = c+d
c_div_d = c/d

In [59]:
print(c_times_d)
print(c_plus_d)
print(c_div_d)

tf.Tensor(
[[1. 2.]
 [0. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 3.]
 [3. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.  2.]
 [inf  4.]], shape=(2, 2), dtype=float32)


In [63]:
# Create Tensors

a = tf.constant([[2,3], [3,3]])
b = tf.constant([[8,7], [2,3]])
x = tf.constant([[-6.89 + 1.78j], [-2.54 + 2.15j]])

In [64]:
# Absolute value of a tensor

abs_x = tf.abs(x)
abs_x

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[7.11621388],
       [3.32777704]])>

In [73]:
# Power of a Tensor

powab = tf.pow(a,2)

In [74]:
powab

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 9],
       [9, 9]], dtype=int32)>

#### Randomly sampled constant Tensors

In [75]:
# Create a tensor with samples from a normal distribution

tn = tf.random.normal(shape=(2,2), mean=0, stddev=1.)

In [76]:
# Create a tensor with samples from a Uniform distribution

tu = tf.random.uniform(shape=(2,1), minval=0, maxval=10, dtype='int32')

In [77]:
# Create a tensor with samples from a poisson distribution

tp = tf.random.poisson((2,2), 5)

In [78]:
tp

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 6.],
       [4., 9.]], dtype=float32)>

In [79]:
# More math operations

d = tf.square(tn)
e = tf.exp(d)
f = tf.cos(c)